version: '3'

services:
  openvpn:
    image: jqtype/openvpn
    restart: always
    env_file:
      - ./openvpn.env
    ports:
      - "1194:1194/udp"
    privileged: true
    container_name: openvpn
    volumes:
      - ./log:/var/log/openvpn
      - ./data/openvpn:/etc/openvpn


